### ISSUE TITLE
How to debug vlcj?

### ISSUE THREAD

**Issue by RogerZheng** [alexa/alexa-avs-sample-app#671] opened 2017-04-10 13:06 UTC
I have trouble in playing prime music,how to debug it?

**Comment by scotthea-amazon** [comment] 2017-04-17 19:56
Hello Roger,

Probably the first place to start is to describe in detail what you are doing and what results you are experiencing.  Usually the next step is to capture inspect logs from the session where the problem is occurring.

Thanks,
-SWH

**Comment by RogerZheng** [comment] 2017-05-02 02:43
thks ,I have modify the source code of vlc to solve it.
Like this:
add propetity in java cmd，-Dvlcj.log=DEBUG

**Comment by namanmittal-namanm** [comment] 2017-05-03 18:21
Hi @RogerZheng, Is the issue resolved, can we close the issue?

**Comment by RogerZheng** [comment] 2017-05-25 01:09
yeah，thks.

**Closed** 2017-05-30 15:09 UTC
