### ISSUE TITLE
ERROR com.amazon.alexa.avs.AVSAudioPlayer - An error occurred while trying to play audio

### ISSUE THREAD

**Issue by RogerZheng** [alexa/alexa-avs-sample-app#691] opened 2017-04-17 08:34 UTC
When playing music in device ,I issue wake command and ask some question.The device could get into trouble and have no sound somehow i do。The error log is like this：

08:27:40.651 [Thread-2413] ERROR com.amazon.alexa.avs.AVSAudioPlayer - An error occurred while trying to play audio
javazoom.jl.decoder.JavaLayerException: cannot obtain source audio line
        at javazoom.jl.player.JavaSoundAudioDevice.createSource(JavaSoundAudioDevice.java:128) ~[jlayer-1.0.1.jar:?]
        at javazoom.jl.player.JavaSoundAudioDevice.writeImpl(JavaSoundAudioDevice.java:148) ~[jlayer-1.0.1.jar:?]
        at javazoom.jl.player.AudioDeviceBase.write(AudioDeviceBase.java:133) ~[jlayer-1.0.1.jar:?]
        at javazoom.jl.player.Player.decodeFrame(Player.java:220) ~[jlayer-1.0.1.jar:?]
        at javazoom.jl.player.Player.play(Player.java:120) ~[jlayer-1.0.1.jar:?]
        at javazoom.jl.player.Player.play(Player.java:104) ~[jlayer-1.0.1.jar:?]
        at com.amazon.alexa.avs.AVSAudioPlayer$5.run(AVSAudioPlayer.java:926) [sample-java-client-20160207.2.jar:?]

**Comment by scotthea-amazon** [comment] 2017-04-19 20:33
Hello RogerZheng,
This sounds like it may be some kind of configuration issue.  Can you provide more details, like what platform you are working on and what steps you are working through?  Also, are there any special steps you need to perform to trigger this error?
-SWH

**Comment by namanmittal-namanm** [comment] 2017-05-03 18:16
Hi @RogerZheng Is your issue resolved? Is for can we close the issue?

**Comment by Jusufs** [comment] 2017-05-11 07:03
Hello,
I have this issue after playing Alexa Itune Radio station after saying Alexa stop.
INFO:WakeWordAgent: IPC Command received:4
INFO:WakeWordAgent: State set to WAKE_WORD_RESUME_REQUESTED(7)
INFO:SensoryWakeWordEngine: handling resume
INFO:SensoryWakeWordEngine: mainLoop thread started
INFO:WakeWordAgent: State set to IDLE(2)
08:50:35.726 [Thread-329] ERROR com.amazon.alexa.avs.AVSAudioPlayer - An error occurred while trying to play audio
javazoom.jl.decoder.JavaLayerException: cannot obtain source audio line
	at javazoom.jl.player.JavaSoundAudioDevice.createSource(JavaSoundAudioDevice.java:128) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.JavaSoundAudioDevice.writeImpl(JavaSoundAudioDevice.java:148) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.AudioDeviceBase.write(AudioDeviceBase.java:133) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.Player.decodeFrame(Player.java:220) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.Player.play(Player.java:120) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.Player.play(Player.java:104) ~[jlayer-1.0.1.jar:?]
	at com.amazon.alexa.avs.AVSAudioPlayer$5.run(AVSAudioPlayer.java:923) [classes/:?]
I have hifiberry audiocard as only one output (default audio card is disabled) and a usb micro.

My audio configs are:
asound.rc
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}
--------------
boot\config.txt
# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
#dtparam=audio=on
dtoverlay=pi3-disable-bt
dtoverlay=hifiberry-dacplus

After failure is still Alexa active (micro input bar on voice service popup is active and commands are responded. Sound-output is broken. If I restart Alexa, all is OK.

**Comment by Jusufs** [comment] 2017-05-11 08:56
I have some issues with hifiberry-plus DAC 
aplay -l
card 0: sndrpihifiberry [snd_rpi_hifiberry_dacplus], device 0: HiFiBerry DAC+ Pro HiFi pcm512x-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: VX800 [Microsoft LifeCam VX-800], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0

Please put your asound.conf here. 
Thanks.

**Comment by elstryan** [comment] 2017-05-11 20:23
Hi @Jusufs, 
I don't have a hifiberry-plus so I can't reproduce this exactly. However I found another post by a different user who is using that component. They've posted a couple suggestions that might fix this for you https://github.com/alexa/alexa-avs-sample-app/issues/284 

Specifically I would first try the apt-get commands they posted and see if that works. Then you can also try the updates to asound.conf that they posted.

**Comment by Jusufs** [comment] 2017-05-13 06:33
Hi elstryan.
Thanks for help :0)

**Comment by elstryan** [comment] 2017-05-13 19:11
No worries! I'll resolve this issue for now. Feel free to re-open if you need anything else.

**Closed by elstryan** 2017-05-13 19:11 UTC

**Comment by gb160** [comment] 2017-11-22 14:56
@RogerZheng It would be great if you could post what changes you made to your .asoundrc file as im having exactly the same issue.
Thanks.
