### ISSUE TITLE
Unable to load VLC Java Error

### ISSUE THREAD

**Issue by Burgeh** [alexa/alexa-avs-sample-app#907] opened 2017-08-23 03:07 UTC
Looked at a few issue threads and saw that people were also having this issue, but the resolution was to add the library path using export. But it has not worked for me.
The troubleshooting steps I followed was:
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install vlc-nox vlc-data
export LD_LIBRARY_PATH=/usr/lib/vlc
export VLC_PLUGIN_PATH=/usr/lib/vlc/plugins
```

When I reboot, these get reset. So on my system the plugin path, sticks but the library path does not, and ends up blank on reboot. So I tried setting it first then running the start up commands for the Alexa AVS sample app and still got the same error.

The error I get it is:
````
> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

Listening on port 3000
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.5
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.RuntimeException: Failed to load the native library.

The error was "Unable to load library 'vlc': Native library (linux-arm/libvlc.so) not found in resource path ([file:/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/target/classes/, 
file:/home/pi/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar, 
file:/home/pi/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar, 
file:/home/pi/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar, 
file:/home/pi/.m2/repository/commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar, 
file:/home/pi/.m2/repository/uk/co/caprica/vlcj/2.4.1/vlcj-2.4.1.jar, 
file:/home/pi/.m2/repository/net/java/dev/jna/platform/3.5.2/platform-3.5.2.jar, 
file:/home/pi/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar, 
file:/home/pi/.m2/repository/javazoom/jlayer/1.0.1/jlayer-1.0.1.jar, 
file:/home/pi/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.11.v20170118/alpn-boot-8.1.11.v20170118.jar, 
file:/home/pi/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar, 
file:/home/pi/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar, 
file:/home/pi/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar, 
file:/home/pi/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.3/log4j-slf4j-impl-2.3.jar, 
file:/home/pi/.m2/repository/org/apache/logging/log4j/log4j-api/2.3/log4j-api-2.3.jar, 
file:/home/pi/.m2/repository/org/apache/logging/log4j/log4j-core/2.3/log4j-core-2.3.jar, 
file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-alpn-client/9.3.7.v20160115/jetty-alpn-client-9.3.7.v20160115.jar, 
file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-http/9.3.7.v20160115/jetty-http-9.3.7.v20160115.jar, 
file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-client/9.3.7.v20160115/http2-client-9.3.7.v20160115.jar, 
file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-http-client-transport/9.3.7.v20160115/http2-http-client-transport-9.3.7.v20160115.jar, 
file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-hpack/9.3.7.v20160115/http2-hpack-9.3.7.v20160115.jar, 
file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-common/9.3.7.v20160115/http2-common-9.3.7.v20160115.jar, 
file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-server/9.3.7.v20160115/jetty-server-9.3.7.v20160115.jar, 
file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-security/9.3.7.v20160115/jetty-security-9.3.7.v20160115.jar, 
file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-servlet/9.3.7.v20160115/jetty-servlet-9.3.7.v20160115.jar, 
file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-util/9.3.7.v20160115/jetty-util-9.3.7.v20160115.jar, 
file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-io/9.3.7.v20160115/jetty-io-9.3.7.v20160115.jar, 
file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-client/9.3.7.v20160115/jetty-client-9.3.7.v20160115.jar, 
file:/home/pi/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar, 
file:/home/pi/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar])".


The required native libraries are named "libvlc.so" and "libvlccore.so".

In the text below <libvlc-path> represents the name of the directory containing "libvlc.so" and "libvlccore.so"...

There are a number of different ways to specify where to find the native libraries:
 1. Include NativeLibrary.addSearchPath("vlc", "<libvlc-path>"); at the start of your application code.
 2. Include System.setProperty("jna.library.path", "<libvlc-path>"); at the start of your application code.
 3. Specify -Djna.library.path=<libvlc-path> on the command-line when starting your application.
 4. Add <libvlc-path> to the system search path (and reboot).

If this still does not work, then it may be necessary to explicitly add the native library directory to the operating
system configuration - e.g. on Linux this might mean setting the LD_LIBRARY_PATH environment variable, or adding
configuration to the "/etc/ld.so.conf" file or the "/etc/ld.so.conf.d" directory. Of these options, setting
LD_LIBRARY_PATH is the only one that would not require root privileges.

Finally, it is not possible to mix CPU architectures - it is not possible for a 64-bit Java Virtual Machine to load
32-bit native libraries.

More information may be available in the log, specify -Dvlcj.log=DEBUG on the command-line when starting your application.

	at uk.co.caprica.vlcj.binding.LibVlcFactory.create(LibVlcFactory.java:191)
	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:213)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.onGetMediaPlayerFactory(AudioMediaPlayerComponent.java:168)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.<init>(AudioMediaPlayerComponent.java:102)
	at com.amazon.alexa.avs.AVSAudioPlayer.setupAudioPlayer(AVSAudioPlayer.java:252)
	at com.amazon.alexa.avs.AVSAudioPlayer.<init>(AVSAudioPlayer.java:143)
	at com.amazon.alexa.avs.AVSAudioPlayerFactory.getAudioPlayer(AVSAudioPlayerFactory.java:18)
	at com.amazon.alexa.avs.AVSController.<init>(AVSController.java:183)
	at com.amazon.alexa.avs.App.<init>(App.java:47)
	at com.amazon.alexa.avs.App.<init>(App.java:36)
	at com.amazon.alexa.avs.App.main(App.java:31)

```

**Comment by FletchNelson** [comment] 2017-08-23 18:55
Are you using the latest N00BS (2.4.3) Raspian "stretch"?  There's some dependency updates that have broken the sample app - a fix is being worked on now.  Try grabbing your OS from here:
https://downloads.raspberrypi.org/NOOBS/images/NOOBS-2017-07-05/

**Comment by Burgeh** [comment] 2017-08-23 20:06
I totally am, I was running my Pi with something else but I decided that a fresh slate probably would've been best so I downloaded the latest raspbian image. I guess that explains it, thank you!
I was racking my brain for a long time about that.

**Comment by juvenile222** [comment] 2017-08-26 18:55
Just got across this comment, banging my head to get this fixed, guess I would wait for the update.

**Comment by Burgeh** [comment] 2017-08-26 20:11
Well, it works fine on the latest Raspbian Jesse. Just gotta use NOOBS to install which take significantly longer than writing the image in my opinion lmao.

**Comment by kencecka** [comment] 2017-08-29 21:26
Glad to year you have it working.  We have an internal ticket to add support for stretch in a future release.

**Comment by Denwen** [comment] 2017-08-30 23:46
I have tried everything I could find about this. Writing image, latest NOOBS and the NOOBS 2.4.2. I still get the very same issue you're reporting. Any ideas as to what I can try?
I'm going a bit crazy here.

**Comment by BennyAvramson** [comment] 2017-09-01 17:29
As a quick solution for running the app on Raspbian Stectch you should create a symbolic link between `libvlc.so` to the specific version of it installed on your environment (e.g. `libvlc.so.5`).

First, find the location of vlc libraries by running: ``ldd `which vlc` ``
Create a symbolic link (Assuming the libraries are in : `/usr/lib/arm-linux-gnueabihf`)
``` bash
cd /usr/lib/arm-linux-gnueabihf
ln -s libvlc.so.5 libvlc.so
```

**Comment by ReelBoxTV** [comment] 2017-09-02 12:48
Thanks ...It worked but I'm getting a new error  no Suchmethod error : sun.security.ssl.SupportedEllipticCurvesExtension.createExtension  method.

**Comment by BennyAvramson** [comment] 2017-09-04 16:39
Hi @ReelBoxTV. Glad it worked for you. Please refer to issue #239 for the other issue you have.

**Comment by BHunter2889** [comment] 2017-09-04 22:06
@BennyAvramson I was having the same issue, but when I ran your commands above, after running `sudo ldconfig` I got the message "ldconfig: /usr/lib/arm-linux-gnueabihf is not a known library type" ... any idea?

**Comment by BennyAvramson** [comment] 2017-09-04 22:39
@BHunter2889, Are you running Raspbian Stretch? Can you send the output of ``ldd `which vlc` ``?

**Comment by BHunter2889** [comment] 2017-09-04 22:58
@BennyAvramson yes, I'm using Stretch. output of the above is as follows:
```
$ ldd `which vlc`
	linux-vdso.so.1 (0x7ec80000)
	/usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76fac000)
	libvlc.so.5 => /usr/lib/arm-linux-gnueabihf/libvlc.so.5 (0x76f81000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76f42000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76f2f000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76df0000)
	/lib/ld-linux-armhf.so.3 (0x76fc1000)
	libvlccore.so.8 => /usr/lib/arm-linux-gnueabihf/libvlccore.so.8 (0x76cfe000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76c7f000)
	librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0x76c68000)
	libidn.so.11 => /lib/arm-linux-gnueabihf/libidn.so.11 (0x76c27000)
	libdbus-1.so.3 => /lib/arm-linux-gnueabihf/libdbus-1.so.3 (0x76bd4000)
	libsystemd.so.0 => /lib/arm-linux-gnueabihf/libsystemd.so.0 (0x76b5a000)
	libselinux.so.1 => /lib/arm-linux-gnueabihf/libselinux.so.1 (0x76b27000)
	liblzma.so.5 => /lib/arm-linux-gnueabihf/liblzma.so.5 (0x76af6000)
	liblz4.so.1 => /usr/lib/arm-linux-gnueabihf/liblz4.so.1 (0x76ad5000)
	libgcrypt.so.20 => /lib/arm-linux-gnueabihf/libgcrypt.so.20 (0x76a05000)
	libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x769d8000)
	libpcre.so.3 => /lib/arm-linux-gnueabihf/libpcre.so.3 (0x7695f000)
	libgpg-error.so.0 => /lib/arm-linux-gnueabihf/libgpg-error.so.0 (0x7693f000)
```

**Comment by ltrain5000** [comment] 2017-09-24 15:58
I was able to recitfy this issue after beating my head against the wall for hours and hours and making seemingly pointless fixes. It is working perfectly now and it has nothing to do with the code. 

Go back into your Amazon Developers Account where you follow these steps:
"In the textbox, next to Allowed Origins enter: https://localhost:3000
In the textbox, next to Allowed Return URLs enter: https://localhost:3000/authresponse"

Once you input the text, click "update" before you hit "save".  If you don't do this, the permissions are not saved and it causes the error.  You must visually verify the permissions are stored, or you will not be able to proceed past the step you are describing.  I believe this is why the solution to this problem is so murky.  It has nothing to do with the error you are receiving.  I was having this problem in both Pi Alexa projects and I realized I made the same mistake on both by erasing everything, deleting each alexa product, starting totally over and confirming I followed all steps thoroughly.  It works perfectly now on both.  I hoe this helps.

**Comment by nunezmanny** [comment] 2017-09-26 21:06
Itrain5000: I made this error too, so I took your suggestion. It looked promising at first but led me to the same error. I'm a NOOB more or less and now I don't know what to do. Any suggestions??

**Comment by ltrain5000** [comment] 2017-09-26 22:33
nunezmanny: Which tutorial are you following?  I suggest [this one](https://pimylifeup.com/raspberry-pi-alexa/) since it also shows how to startup the AlexaPi on boot disconnected from the monitor.  I do know the other tutorials use a different directory location for storing the AVS files, so be sure not to mismatch code from different tutorials.  

Trust me, I am likely a bigger noob than you and probably the least qualified to give advice on this.  I just shared my experience hoping others would be able to benefit.  I reformatted, loaded noobs onto the disc, went into Amazon developer services and deleted my first projects and started over, confirmed 100% I was updating the permissions before I clicked save.  Then started from scratch pasting the code.  Are your Secret ID and Product ID accurate? I'd suggest making sure the "Product ID" is the name on the second line  on the "manage page" of your device in Developer Services" and you're not not inputting the "Product Name" from the first line.  That part screwed me up originally as well.  Try that and let us know.  It has to be something simple like I was dealing-- It seems like every other person on the internet is building their own Alexa.  If they can do it, we can do it!

**Comment by mradulan** [comment] 2017-09-26 23:03
@nunezmanny please update and close the issue if it gets fixed for you.

**Comment by nunezmanny** [comment] 2017-09-26 23:42
Hey, thanks for your reply. I am indeed using that very tutorial. I did not use noobs because I already had a clean copy of raspbian stretch from just this morning. Is it important to load it from noobs? Otherwise, how do I delete developer projects? I could only see "metrics" or "manage" links. Codes should be accurate since I CTRL-C and CTRL-V them. Product names and product ID are the same. Should they be different? You're right about everyone building alexa ... makes it seem like it should be easy, but in fact it's always quite intricate. SMH!

**Comment by ltrain5000** [comment] 2017-09-27 00:07
OK. I just went back into Developer Services to make sure I was giving 100% accurate information- I actually didn't delete, I just made a new product, however, I want to correct something I misspoke about earlier that possibly led you down the wrong path. if you log into Amazon Developer Services, Go to Alexa, Click on Get Started, Go to Manage next to your Device, go to Security Profile, 
"In the textbox, next to Allowed Origins enter: https://localhost:3000
In the textbox, next to Allowed Return URLs enter: https://localhost:3000/authresponse"

Here is where I screwed up above-  Click "ADD" **Before** "Update" for both permissions.  I am sorry as I was going off of memory and was excited I got it working.  Can you try that? I apologize for that-- I edited my first post.

**Comment by nunezmanny** [comment] 2017-09-27 02:22
No,no worries. It was easy to understand and I actually knocked it out on
the first go. Thanks for that!

**Comment by nunezmanny** [comment] 2017-09-27 02:25
No, it was perfectly fine. In fact, it was good enough for me to change. Thanks for that. Otherwise, it still didn't fix my problem and the conclusion that I've come to is that it's a Raspbian Stretch problem. I think I'm gonna revert back to Jessie tmrw and see how far that takes me...

**Comment by mradulan** [comment] 2017-09-27 05:38
Closing the issue for now. Please reopen if the issue persists.

**Closed by mradulan** 2017-09-27 05:38 UTC

**Comment by ltrain5000** [comment] 2017-09-27 09:27
I am using Jessie.  Directly from the Rasperry Pi site.

**Comment by bodudek-mediegruppen** [comment] 2017-10-12 15:31
@ltrain5000 Did you find a solution? I am also on Jessie directly from website, but I get the exact same error.
