### ISSUE TITLE
clean install to rpi jessie can't find wiringpi.h

### ISSUE THREAD

**Issue by Petr2** [alexa/alexa-avs-sample-app#696] opened 2017-04-18 09:38 UTC
I see there is an outstanding pull request from December, #438, that has not been done that would, presumably, fix this.

**Comment by scotthea-amazon** [comment] 2017-04-18 16:13
This is a duplicate of #438.   That issue will be closed when the pull request is included in a release.  Closing this issue.

**Closed by scotthea-amazon** 2017-04-18 16:13 UTC
