### ISSUE TITLE
Login to Alexa App and change settings

### ISSUE THREAD

**Issue by marculos** [alexa/alexa-avs-sample-app#482] opened 2017-01-19 22:00 UTC
Hi, I have made some progress! So I have Alexa working ish and responding to voice requests. 

What I can't get working is the Alexa app. If I can't register the pi as an echo how do I configure it in the app ? 

It is showing the Pi as offline, and the to lists etc don't work. I am stuck with Seattle too for the region, timezone etc. 

Any ideas here ?

**Comment by PtrBld** [comment] 2017-01-20 09:21
Are you using an UK or German amazon account? If so yo are not able to use the app as intended.
Refer to #297

**Comment by marculos** [comment] 2017-01-20 10:10
I created an account at developer.amazon.com which I assumed was a US developer account ? Thanks for the link will check it out

**Comment by derdude01** [comment] 2017-01-22 11:06
I'm also using my (german) account. Is it possible, if using an US account, to switch the location (and also the language) to german with the Android Alexa App?

**Comment by SamuelBrucksch** [comment] 2017-01-22 18:28
App can not work together with raspi alexa, as device is shown as offline. Also if setting up calendar and so on raspi alexa can not access it so you can only use the basic functionality.

**Comment by PtrBld** [comment] 2017-01-22 18:35
But it will work when avs is officially available in Germany/UK, right?

**Comment by SamuelBrucksch** [comment] 2017-01-22 18:52
not sure but i dont think so. actually the difference in language should only restrict skills that are not ready for multiple languages or so. I think the app really only works with real devices but i'm not 100% sure as i just started with raspi alexa this weekend. but i guesws if a US account would work someone woul have written here already... actually i think in my developer account i specified US because of the free US tier. but maybe that was something else...

**Comment by umma08** [comment] 2017-01-23 10:48
Hi all, i got the address to change using the web interface alexa.amazon.com. It now gives me local weather, and information, as it knows where i am. However, it doesn't seem to recognise any changes i make regarding the flash briefings and added skills. Anybody know why/a fix?

**Comment by keleric** [comment] 2017-01-25 00:54
When AVS for the UK and Germany launches (planned early this year), you should have full support within the Alexa app (alexa.amazon.com or the phone apps). As far as account goes, both the developer account on developer.amazon.com and the account you sign into on the Raspberry Pi should be amazon accounts that were associated with the US (made at amazon.com, not amazon.co.uk, for instance).

**Comment by keleric** [comment] 2017-01-27 18:41
Closing this issue since it seems to be related to the upcoming internationalization release. If you're still seeing problems after that launch, please file a new Github issue.

**Closed by keleric** 2017-01-27 18:41 UTC
Labels: Authorization, Internationalization

**Comment by SamuelBrucksch** [comment] 2017-02-03 20:36
Alexa App on Android now works with raspi avs when locale is set to german in latest changes. Also german is supported now and seems to work quite well.

**Comment by marculos** [comment] 2017-02-08 08:52
AVS now has support for UK, do I need to make changes to the Pi to make this work for the UK ?

**Comment by SamuelBrucksch** [comment] 2017-02-08 08:57
No, just clone latest repository and then select the correct locale with install script.

**Comment by umma08** [comment] 2017-02-08 17:33
@SamuelBrucksch i cloned the latest repository, updated my details in the install.sh script, and then attempted to run the first terminal command to start the companionService, and got then got a host of errors. 

`pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples $ cd companionService && npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.


module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/app.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.38+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0
`

**Comment by SamuelBrucksch** [comment] 2017-02-08 17:54
Did you actually run the install script after adjusting the values? -> ``. automated_install.sh``

**Comment by umma08** [comment] 2017-02-08 17:55
@SamuelBrucksch oh, i have to run the whole install script again. Lmao. I am an idiot.

**Comment by SamuelBrucksch** [comment] 2017-02-08 17:57
Yes, the script just installs everything and stores the vales you entered in that script in different config files. Its just making it easier for you so you dont have to enter the same in multiple locations.

**Comment by umma08** [comment] 2017-02-08 20:25
@SamuelBrucksch  Got it working. Seems to be going pretty much perfectly. thanks!

**Comment by marculos** [comment] 2017-02-10 11:07
Sorry to be a dumbass .. @umma08 what do you need to do in order to get this working ?

How do I do below so my Pi Echo works for UK ?
clone latest repository and then select the correct locale with install script.

Many thanks

**Comment by umma08** [comment] 2017-02-10 13:01
@marculos i cloned the latest repository onto my desktop on the Pi. using this command in terminal (i moved th old folder away from desktop so there wouldn't be a conflict)

cd Desktop
git clone https://github.com/alexa/alexa-avs-sample-app.git

i then filled in the details in the automated_install.sh file using this command

cd ~/Desktop/alexa-avs-sample-app
nano automated_install.sh

here is where you put your productID, Client ID, and clientSecret - as you did the first time. 

i then ran the automated_install.sh script using this command in terminal. 

cd ~/Desktop/alexa-avs-sample-app
. automated_install.sh

during the install, it asks you for location. 1)US, 2)UK, 3)Ger

the install then takes place (it is much shorter than the first time you did it, as most of the dependencies are already in place). 

then you start up using the normal procedure. found here 
https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi

to add skills, go to 

alexa.amazon.co.uk on a browser (i did it from my home computer)

log in using your amazon details, and add skills, and your home address to the alexaPi. 

that should work.

**Comment by derdude01** [comment] 2017-02-11 17:27
@umma08 Hope, it works. If you've already installed cloned the repository, you can also make a "force pull":
1. Go to your alexa folder
2. Type "git fetch --all"
3. Type "git reset --hard origin/master"
That overwrites the local changes with the new files on the remote.
