### ISSUE TITLE
How to install on Raspbian Stretch

### ISSUE THREAD

**Issue by WeCreate180** [alexa/alexa-avs-sample-app#1066] opened 2017-12-22 19:31 UTC
Hello! The error for the mvn exec:exec command is because Java won't install! This is because Amazon didn't add an update to the install-java8.sh file yet. However, YOU can!

Edit the file: alexa-avs-sample-app/samples/javaclient/install-java8.sh

Find the line that says: 

```
elif [ "$VERSION" == "jessie" ]; then
    UBUNTU_VERSION="trusty"
```

Add the following below that line:

```
elif [ "$VERSION" == "stretch" ]; then
    UBUNTU_VERSION="yakkety"

```
Save the file, and run the automated install once again. This time, it will work.

(I have created a pull request for them to add this, but for now. You must do this.)

**Comment by kjkh** [comment] 2017-12-22 23:58
Hi @WeCreate180,

Thank you for the pull request. Our process is to make changes internally and run all test before pushing the change to github in the form of a new release. I have added this to our internal tracking system to be assessed and prioritized.

**Comment by kjkh** [comment] 2017-12-24 22:58
Reopening for convenience of future users. Should close once this has been addressed in a future release.

**Comment by kclchan** [comment] 2018-01-02 19:44
Hi @WeCreate180, would you be able to let us know how did you install stretch on your pi?  We couldn't reproduce the issue you are seeing, and as far as we know, a correct version of Java is included as part of the stretch image.

**Comment by WeCreate180** [comment] 2018-01-08 20:22
@kclchan I installed by downloading the pixel desktop stretch image off of Raspbian official website. I followed your guide and couldn’t run the client. I found out the java that you guys had wouldn’t install on stretch since you don’t support it yet in your install-java8.sh file. Made a few edits and it worked

**Comment by noemu** [comment] 2018-01-09 11:27
on stretch lite run this before installation and add the stretch part as sugggested in 1. post:
```sudo apt-get install dirmngr```

**Comment by BennyAvramson** [comment] 2018-01-11 02:04
Hi All,

The issue is due to the Lite version is shipped without JDK. We'll fix this on our next release. Meanwhile, you can try the solution suggested here at https://github.com/alexa/alexa-avs-sample-app/issues/1066#issue-284235943 and https://github.com/alexa/alexa-avs-sample-app/issues/1066#issuecomment-356257919

**Comment by bandkenamazoncom** [comment] 2018-01-24 18:25
Closing due to inactivity.  Please feel free to reopen if there is any additional issues.

**Closed by bandkenamazoncom** 2018-01-24 18:25 UTC
