### ISSUE TITLE
wake word not working

### ISSUE THREAD

**Issue by flagtrax** [alexa/alexa-avs-sample-app#1053] opened 2017-12-14 04:43 UTC
I,m fairly new to the Pi world, and the alexa project. I have the basic thing working but I tried both wakeWord engines and neither work. I can click the "Tap to speak" button and get a response so it seems all is working but the wakeWord engine. I'm using a Pi 2B, and usb mic and audio out on the audio jack. Any help appreciated.

**Comment by flagtrax** [comment] 2017-12-14 21:31
Here is the output from the 3rd terminal screen when invoking the startup of wakeWord.....
INFO:main: Starting Wake Word Agent
INFO:WakeWordAgent: State set to IDLE(2)
INFO:Initializing Sensory library | library name: TrulyHandsfree | library version: 5.0.0-beta.10.2 | model file: ../ext/resources/spot-alexa-rpi.snsr
WARNING:Library expires on: License expires on 28 Mar 2018 00:00:00 GMT
INFO:SensoryWakeWordEngine: mainLoop thread started
ERROR:An error happened in the mainLoop of SensoryWakeWord snsrRun(): task: Input channel audio-pcm: ALSA error: No such file or directory
INFO:SensoryWakeWordEngine: mainLoop thread ended
INFO:WakeWordIPCSocket::mainLoop thread started
INFO:WakeWordIPCSocket: init socket on port:5123
INFO:===> Connected to AVS client <===
INFO:WakeWordAgent: thread started

**Comment by sanjayrd** [comment] 2017-12-15 20:31
Hi @flagtrax,

I believe this [issue](https://github.com/alexa/alexa-avs-sample-app/issues/551) and this [issue](https://github.com/alexa/alexa-avs-sample-app/issues/533) should be able to help you out as they faced the exact same issues. Please check these out to see if they help.

Thanks,
Sanjay

**Comment by bitstomp** [comment] 2018-07-18 02:22
I solved this problem by running the command to start Sensory with sudo, like so: `cd wakeWordAgent/src && sudo ./wakeWordAgent -e sensory`

**Comment by BennyAvramson** [comment] 2018-07-18 21:06
Hi @flagtrax,

As you didn't re-raise the issue, I'm assuming the issue is solved and I'm closing the issue. Please reopen it if it still occurs.

Thanks,
Benny

**Closed by BennyAvramson** 2018-07-18 21:06 UTC
