### ISSUE TITLE
Run the Client - Fails 

### ISSUE THREAD

**Issue by NeilWBruce** [alexa/alexa-avs-sample-app#140] opened 2016-04-18 21:58 UTC
All,

I've run through all the Steps until in come to running the command 
mvn exec:exec

When I get the error 

exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.

I'm running from PuTTy on a Windows machine.  So close yet so far

**Comment by Cory-Christensen** [comment] 2016-04-19 03:33
I ran into this same issue. The problem is that SSH is not configured to set up an X11 display for you. As a workaround I use the TightVNC viewer to work in the Pi - or even just hooked the pi up to a display itself. 
I'm not sure if there's a way to set up SSH to allow X11 windows, but maybe one of the geniuses hanging around here can help you out.

**Comment by rgruskin** [comment] 2016-05-05 02:47
I am getting this same message even when I hooked up a display and worked directly on the Pi.  Any ideas?

**Comment by xelfer** [comment] 2016-08-09 00:58
old question but this is solved by exporting the display environment variable before running mvn exec:exec

try:
export DISPLAY=:1 

and when you run mvn it will load your java application into your vnc session display.

**Comment by ajotwani** [comment] 2016-10-06 13:09
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Closed by ajotwani** 2016-10-06 13:09 UTC
Labels: status: avs-question, X11
