### ISSUE TITLE
The required native libraries are named "libvlc.so" and "libvlccore.so".

### ISSUE THREAD

**Issue by lucastanure** [alexa/alexa-avs-sample-app#842] opened 2017-07-03 10:47 UTC
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.4
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.RuntimeException: Failed to load the native library.

The error was "Unable to load library 'vlc': Native library (linux-arm/libvlc.so) not found in resource path ([file:/home/alexa/alexa-avs-sample-app/samples/javaclient/target/classes/, file:/home/alexa/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar, file:/home/alexa/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar, file:/home/alexa/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar, file:/home/alexa/.m2/repository/commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar, file:/home/alexa/.m2/repository/uk/co/caprica/vlcj/2.4.1/vlcj-2.4.1.jar, file:/home/alexa/.m2/repository/net/java/dev/jna/platform/3.5.2/platform-3.5.2.jar, file:/home/alexa/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar, file:/home/alexa/.m2/repository/javazoom/jlayer/1.0.1/jlayer-1.0.1.jar, file:/home/alexa/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.11.v20170118/alpn-boot-8.1.11.v20170118.jar, file:/home/alexa/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar, file:/home/alexa/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar, file:/home/alexa/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar, file:/home/alexa/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.3/log4j-slf4j-impl-2.3.jar, file:/home/alexa/.m2/repository/org/apache/logging/log4j/log4j-api/2.3/log4j-api-2.3.jar, file:/home/alexa/.m2/repository/org/apache/logging/log4j/log4j-core/2.3/log4j-core-2.3.jar, file:/home/alexa/.m2/repository/org/eclipse/jetty/jetty-alpn-client/9.3.7.v20160115/jetty-alpn-client-9.3.7.v20160115.jar, file:/home/alexa/.m2/repository/org/eclipse/jetty/jetty-http/9.3.7.v20160115/jetty-http-9.3.7.v20160115.jar, file:/home/alexa/.m2/repository/org/eclipse/jetty/http2/http2-client/9.3.7.v20160115/http2-client-9.3.7.v20160115.jar, file:/home/alexa/.m2/repository/org/eclipse/jetty/http2/http2-http-client-transport/9.3.7.v20160115/http2-http-client-transport-9.3.7.v20160115.jar, file:/home/alexa/.m2/repository/org/eclipse/jetty/http2/http2-hpack/9.3.7.v20160115/http2-hpack-9.3.7.v20160115.jar, file:/home/alexa/.m2/repository/org/eclipse/jetty/http2/http2-common/9.3.7.v20160115/http2-common-9.3.7.v20160115.jar, file:/home/alexa/.m2/repository/org/eclipse/jetty/jetty-server/9.3.7.v20160115/jetty-server-9.3.7.v20160115.jar, file:/home/alexa/.m2/repository/org/eclipse/jetty/jetty-security/9.3.7.v20160115/jetty-security-9.3.7.v20160115.jar, file:/home/alexa/.m2/repository/org/eclipse/jetty/jetty-servlet/9.3.7.v20160115/jetty-servlet-9.3.7.v20160115.jar, file:/home/alexa/.m2/repository/org/eclipse/jetty/jetty-util/9.3.7.v20160115/jetty-util-9.3.7.v20160115.jar, file:/home/alexa/.m2/repository/org/eclipse/jetty/jetty-io/9.3.7.v20160115/jetty-io-9.3.7.v20160115.jar, file:/home/alexa/.m2/repository/org/eclipse/jetty/jetty-client/9.3.7.v20160115/jetty-client-9.3.7.v20160115.jar, file:/home/alexa/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar, file:/home/alexa/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar])".

The required native libraries are named "libvlc.so" and "libvlccore.so".

In the text below <libvlc-path> represents the name of the directory containing "libvlc.so" and "libvlccore.so"...

There are a number of different ways to specify where to find the native libraries:
 1. Include NativeLibrary.addSearchPath("vlc", "<libvlc-path>"); at the start of your application code.
 2. Include System.setProperty("jna.library.path", "<libvlc-path>"); at the start of your application code.
 3. Specify -Djna.library.path=<libvlc-path> on the command-line when starting your application.
 4. Add <libvlc-path> to the system search path (and reboot).

If this still does not work, then it may be necessary to explicitly add the native library directory to the operating
system configuration - e.g. on Linux this might mean setting the LD_LIBRARY_PATH environment variable, or adding
configuration to the "/etc/ld.so.conf" file or the "/etc/ld.so.conf.d" directory. Of these options, setting
LD_LIBRARY_PATH is the only one that would not require root privileges.

Finally, it is not possible to mix CPU architectures - it is not possible for a 64-bit Java Virtual Machine to load
32-bit native libraries.

More information may be available in the log, specify -Dvlcj.log=DEBUG on the command-line when starting your application.

        at uk.co.caprica.vlcj.binding.LibVlcFactory.create(LibVlcFactory.java:191)
        at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:213)
        at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.onGetMediaPlayerFactory(AudioMediaPlayerComponent.java:168)
        at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.<init>(AudioMediaPlayerComponent.java:102)
        at com.amazon.alexa.avs.AVSAudioPlayer.setupAudioPlayer(AVSAudioPlayer.java:252)
        at com.amazon.alexa.avs.AVSAudioPlayer.<init>(AVSAudioPlayer.java:143)
        at com.amazon.alexa.avs.AVSAudioPlayerFactory.getAudioPlayer(AVSAudioPlayerFactory.java:18)
        at com.amazon.alexa.avs.AVSController.<init>(AVSController.java:181)
        at com.amazon.alexa.avs.App.<init>(App.java:65)
        at com.amazon.alexa.avs.App.<init>(App.java:53)
        at com.amazon.alexa.avs.App.main(App.java:48)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.088 s
[INFO] Finished at: 2017-07-03T10:46:56+00:00
[INFO] Final Memory: 7M/19M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by lucastanure** [comment] 2017-07-03 10:48
sudo ldconfig -p | grep vlc

        libvlccore.so.8 (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libvlccore.so.8
        libvlc_vdpau.so.0 (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/vlc/libvlc_vdpau.so.0
        libvlc_vdpau.so (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/vlc/libvlc_vdpau.so
        libvlc.so.5 (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libvlc.so.5

**Comment by lucastanure** [comment] 2017-07-03 10:49
VLC_PLUGIN_PATH="/usr/lib/arm-linux-gnueabihf/vlc/plugins/"
LD_LIBRARY_PATH="/usr/lib/arm-linux-gnueabihf/vlc/"

**Comment by mradulan** [comment] 2017-07-05 21:07
do you mean your native libraries are "libvlccore.so.8" and "livvlc.so.5" instead of *.so?

**Comment by lucastanure** [comment] 2017-07-06 08:19
Changed from stretch to jessie and got working

**Comment by mradulan** [comment] 2017-07-06 18:12
if this is resolved, can you close the issue. Thanks.

**Closed** 2017-07-06 18:58 UTC

**Comment by dcwang1224** [comment] 2017-08-29 14:34
Hi 
I got exact same problem but I got my vlc version as "ldconfig -p | grep vlc" below ->
root@localhost:/# ldconfig -p | grep vlc
        libvlccore.so.7 (libc6,AArch64) => /usr/lib/libvlccore.so.7
        libvlc.so.5 (libc6,AArch64) => /usr/lib/libvlc.so.5

And I did config my "LD_LIBRARY_PATH" and "VLC_PLUGIN_PATH" ->
root@localhost:/# echo $LD_LIBRARY_PATH
/usr/lib/
root@localhost:/# echo $VLC_PLUGIN_PATH
/usr/lib/vlc/plugins/

Do i need to reinstall libvlccore.so.8 ? And did those config again ?
My platform is ubuntu arm64

**Comment by BHunter2889** [comment] 2017-09-04 19:15
Going from the resolution comment of the OP, It appears the issue is related to the guide being written for Raspbian Jessie and the setup process is not compatible with the latestest version which is Raspbian Stretch. 

I wonder if this has something to do with the *.so.8 and .so.5 VLC namings? @mradulan can you comment on this since you were eluding to it? 

I'm also experiencing the same issue.
