### ISSUE TITLE
java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by YOUN3SS** [alexa/alexa-avs-sample-app#514] opened 2017-02-03 21:02 UTC
Does anyone has a pop-up with this error?
"java.util.concurrent.TimeoutException"

I'm using a fresh Raspbian and I see no known problem here.
(audio output OK, audio input OK, internet connection OK, token OK)

**Comment by SamuelBrucksch** [comment] 2017-02-03 22:51
Maybe network problems. You have the full error?

**Comment by YOUN3SS** [comment] 2017-02-04 09:06
No it is not due to network, I can sign in for tokens.

Two things I changed, and now Alexa is OK:
- I start Alexa directly in the Raspberry Pi without VNC
- I clean up my browser in order to enter again my Amazon credentials
I can't see that the problem is due to above points, but they are all what I did.

I didn't save the full errors sorry...
Issue can be closed.

**Comment by umma08** [comment] 2017-02-11 17:06
i am getting this issue as well 

java.util.concurrent.TimeoutException

it is happening after about 24 hours of the Pi running and alexa working fine. Any ideas anybody?

**Comment by umma08** [comment] 2017-02-11 17:07
@YOUN3SS how did you get the Pi to start Alexa without VNC? Did you write an auotmated process for the terminal commands?

**Comment by YOUN3SS** [comment] 2017-02-22 08:49
I did it with HDMI monitor.
I don't think that this Alexa project can be started without a display.
If you want to use Alexa without screen, try the project AlexaPi.
https://github.com/sammachin/AlexaPi

**Comment by britdub** [comment] 2017-02-22 16:37
after a few hours I get this problem @SamuelBrucksch how do I find the full error?
I'm still new to Linux but keen to learn

**Comment by SamuelBrucksch** [comment] 2017-02-22 17:21
@britdub its a Java error so you have to check the logs from java, no idea if they are stored and where.

**Comment by Alexnagel** [comment] 2017-02-22 17:40
@britdub @samuelBrucksch they are located in `alexa-avs-sample-app/samples/javaclient/logs` where `application.log` is the latest.

**Comment by elstryan** [comment] 2017-03-15 19:36
Hi Folks, 
Are you still running into this issue?

**Comment by elstryan** [comment] 2017-03-15 20:38
@umma08 
Since you original posted the issue the service has undergone some updates that may address this problem. Please try again and let us know please.

**Comment by umma08** [comment] 2017-03-27 13:49
@elstryan I have been running my Pi based Alexa for a few days now (about 72+ hours). It has not encountered the issue as yet. I will update if it does.

**Comment by yugoren** [comment] 2017-03-27 15:18
@umma08: Great news! We'll close this issue for now.
Anyone: Feel free to re-open if the same issue persists.

**Closed by yugoren** 2017-03-27 15:18 UTC

**Comment by gopal-amlekar** [comment] 2017-04-03 12:40
Hi, I am having this issue today for quite  a long time. It doesn't go ahead. The log file is attached.  [log.txt](https://github.com/alexa/alexa-avs-sample-app/files/890025/log.txt)
One observation is, after you speak the app doesn't recognize this as speech ended (the progress bar still keeps moving listening to audio). 
It has worked earlier fine but the exception did occur earlier also. Today it is continuously showing up.

**Comment by Pukington** [comment] 2017-04-14 07:27
I have this issue also.  It works for a few hours, even occasionaly a day, then the Java app pops up with java.util.concurrent.timeoutexception.

I concur with @gopal-amlekar, this feels like Alexa doesn't realise you stop speaking and keeps listening, then timeouts.  It's rather annoying.

**Comment by gopal-amlekar** [comment] 2017-04-14 08:10
Have a look at #602. It seems it is duplicate of this issue. Which country you are in @Pukington? See if your country is supported.

**Comment by Pukington** [comment] 2017-04-14 09:34
Thanks @gopal-amlekar, I'm in Australia.  I have increased the timeout in AVSClient.java so shall see how i get one, I appreciate the pointer, thanks!

**Comment by gopal-amlekar** [comment] 2017-04-14 09:41
Pleasure..

Okay, can you please do let me know if there is any improvement with the timeout change? I haven't yet tried it.

**Comment by tsathish123** [comment] 2017-05-03 09:03
I end up in same issue. I am working from India. Is there any improvement with the changes in timeout value?

**Comment by gopal-amlekar** [comment] 2017-05-04 07:21
@tsathish123 , I have stopped working on it currently. It is better to wait for Alexa to be supported from India properly.

**Comment by tsathish123** [comment] 2017-05-10 01:41
@gopal-amlekar : I did some additional changes in my settings and now AVS is working for me from India itself. I ran automated_install.sh script (Even though i am not using Raspberry PI) and then i started the companionservice and client service, now it is working. It could recognize my voice and giving the response as expected. I dont see timeout error any more.

**Comment by gopal-amlekar** [comment] 2017-05-11 06:17
Well, getting it to work isn't a problem. I had it working as well. The problem is intermittently the server may not be able to fulfill your request. So if you keep it running for a few hours, or sometimes during peak load, the service may not work if you are in non-supported zone. 
Thanks for the update.

**Comment by Pukington** [comment] 2017-05-11 06:44
@gopal-amlekar Sorry for the late update, unfortunately i've had a few restarts on my pi in the last month.  Current running time is up for eight days without a timeout situation having updated the java conf file.  I'll report further as not planning on a restart anytime soon.

**Comment by tweaty100** [comment] 2017-07-24 08:46
@tsathish123 
will you please explain it in detail how could you did this please.as i ahaving similar issue since long but not working at all .please help.

Thanks in advance

**Comment by tweaty100** [comment] 2017-07-24 08:52
@gopal-amlekar 
you said this works for you will you please help me how could it work for you as i am also facing same issue .please help
Thanks in advance

**Comment by tsathish123** [comment] 2017-07-24 09:16
@tweaty100 : Please follow this step "I ran automated_install.sh script (Even though i am not using Raspberry PI) and then i started the companionservice and client service, now it is working"

**Comment by gopal-amlekar** [comment] 2017-07-24 09:21
@tweaty100: Follow the steps using automated installer. It should work.
Sometimes it doesn't give response but that is down to net connectivity or
some bugs in the Alexa sample app. I have been using another hardware last
couple of months and it is working perfect now.
If you still can't get it to work, post your all details and the exact
problem to help others help you.

**Comment by tweaty100** [comment] 2017-07-24 09:34
@tsathish123  whuch board you using ?
is it dragonboard?

**Comment by tweaty100** [comment] 2017-07-24 09:35
@gopal-amlekar yes i am running but its almost 20-30 minutes it is still running? will it going to change  my prior settings?
Thanks

**Comment by gopal-amlekar** [comment] 2017-07-24 09:38
Can't understand what you are trying to say @tweaty100. Sometimes a simple
restart also solves problems. If not you may try re-installing everything
using the automated installer script.

**Comment by tweaty100** [comment] 2017-07-24 09:55
@tsathish123 
 i tried according to your steps but that wont even rum "mvn exec:exec " command?
@gopal-amlekar i meant i ran automated_install.sh but it is took too much time as well as it just changed my settings as now mvn exec:exec is also not working ?

**Comment by gopal-amlekar** [comment] 2017-07-24 10:00
Run everything again. That automated installer takes long time, few hours..
Be patient with it.

**Comment by tweaty100** [comment] 2017-07-24 10:08
@gopal-amlekar 
is it any command to undo all changes?

**Comment by gopal-amlekar** [comment] 2017-07-24 12:57
Not aware of any such command for this setup.But better way you can start
afresh in a new folder.
