### ISSUE TITLE
Max request per destination 1024 exceeded

### ISSUE THREAD

**Issue by jwballan** [alexa/alexa-avs-sample-app#503] opened 2017-01-30 14:35 UTC
I just installed and started Alexa on a rasberry PI and get  the Alexa Voice Serve window.
When I click listen, I get the "ping" from the speaker but when I say something, I
get an error of:

java.util.concurrent.ExectionException:
 java.util.concurrent.RejectedExcecutionException:
 Man request per destination 1024 exceeded for HttpDestination [https://avz-alexa-na.amazon]8f622f, queue=1024

**Comment by jwballan** [comment] 2017-01-30 16:36
Attached is the application log from javaclient.  If another is needed, please let me know the
location.
Thank you

[alexa_application-log.txt](https://github.com/alexa/alexa-avs-sample-app/files/739557/alexa_application-log.txt)

**Comment by jwballan** [comment] 2017-01-31 13:01
Not resolved, still open

**Comment by 1rvy** [comment] 2017-02-14 16:34
Also getting this periodically since upgrading AVS and moving to alexa.amazon.co.uk from alexa.amazon.com

**Comment by mrtheduke** [comment] 2017-02-23 08:36
Like 1vry, I've been getting this (as well as timeout exceptions) since upgrading AVS and moving to alexa.amazon.co.uk from alexa.amazon.com.

**Comment by Gunwoody** [comment] 2017-02-23 10:18
Same here - anyone got any update on this?

**Comment by aycgit** [comment] 2017-03-08 12:08
Same here, have you found a fix? Im running newest raspian

**Comment by allusernamestakenexceptthis** [comment] 2017-03-09 13:42
same here

**Comment by DavidM42** [comment] 2017-03-11 19:53
From what I found out about this problem yet I can say that a reboot fixes the problem for now althought it probably comes back.
Also it seems that it could either be a set maximal limit in the application code or in Linux/Debian/Raspian itself.
Which systems are you all using, maybe it's the OSes fault. (Im using newest Raspian with pixel)

**Comment by elstryan** [comment] 2017-03-15 19:33
Hi Folks, 
I'm having trouble reproducing this right now. Can you please try again and let us know if you are still encountering this issue?

**Comment by DavidM42** [comment] 2017-03-16 21:40
@elstryan Interestingly the issue has disappeared for me.
I just started the sample app today after not using it for a while and I don't get this issue anymore.

**Comment by elstryan** [comment] 2017-03-16 21:43
Thanks! Marking the issue as closed for now.

**Closed by elstryan** 2017-03-16 21:43 UTC
