### ISSUE TITLE
Please include wiringpi in the install script

### ISSUE THREAD

**Issue by martinfandel** [alexa/alexa-avs-sample-app#531] opened 2017-02-11 12:49 UTC
Hi,

please include wiringpi in the install script. Otherwise the compile of the wakeword fails.

Thank you!

BR

Martin

**Comment by jordan-heier** [comment] 2017-03-29 16:53
This is related to pull request https://github.com/alexa/alexa-avs-sample-app/pull/438. Will keep this issue open until the pull request has been accepted.

**Comment by scotthea-amazon** [comment] 2017-04-18 16:12
This is a duplicate of #438.   That issue will be closed when the pull request is included in a release.  Closing this issue.

**Closed by scotthea-amazon** 2017-04-18 16:12 UTC
Labels: Configuration, Raspbian, Wake Word
