### ISSUE TITLE
Uninstall Alexa on Ubuntu 16.04

### ISSUE THREAD

**Issue by GokulSakthivel** [alexa/alexa-avs-sample-app#1044] opened 2017-12-05 17:14 UTC
I want to completely remove alexa on ubuntu.I does n't know that where the alexa library present in my Ubuntu computer. Please help me to completely remove alexa from by Ubuntu system...!

**Comment by scotthea-amazon** [comment] 2017-12-05 19:02
Hello GokulSakthivel,

First, am assuming here that you are working from the instructions on the [Linux Getting Started](https://github.com/alexa/alexa-avs-sample-app/wiki/Linux) page.

Here are the things you will want to do:

- Delete the **{REFERENCE_IMPLEMENTATION}** directory (i.e. where the source was git-cloned to).
- If you installed VLC and no longer want it, uninstall it.  Also remove the **VLC_PLUGIN_PATH** environment variable, and remove /usr/lib/vlc from **LD_LIBRARY_PATH**.
- If you installed Node, and no longer want it, uninstall it.
- If you installed the JDK, and no longer want the it, uninstall it.
- If you installed Maven, and no longer want it, uninstall it.
- If you installed Android Studio, and no longer want it, uninstall it.
- If you installed Xcode 7 and no longer want it, uninstall it.

I hope that helps,
-SWH

**Comment by GokulSakthivel** [comment] 2017-12-09 16:01
thank you.....

**Comment by scotthea-amazon** [comment] 2017-12-11 19:45
Hello GokulSakthivel,

It sounds like the issue is resolved for you, so I am closing it.  If I have closed it in error, please feel free to re-open it.

Thank you,
-SWH

**Closed** 2017-12-11 19:44 UTC
