### ISSUE TITLE
In step 7-cd javaclient && mvn exec:exec I got some error like c:exec /opt/java/jdk1.8.0_121/bin/java: 6: /opt/java/jdk1.8.0_121/bin/java: Syntax error: ")" unexpected

### ISSUE THREAD

**Issue by RP2110** [alexa/alexa-avs-sample-app#569] opened 2017-02-28 12:56 UTC

**Comment by elstryan** [comment] 2017-03-14 22:15
Hi @RP2110 
This looks like a duplicate of this issue: https://github.com/alexa/alexa-avs-sample-app/issues/572 I'll close this instance and we can continue the conversation of #572

**Closed by elstryan** 2017-03-14 22:15 UTC
Labels: Configuration
