### ISSUE TITLE
I have trouble playing m3u8 stream, like prime music.

### ISSUE THREAD

**Issue by zyh201007** [alexa/alexa-avs-sample-app#668] opened 2017-04-08 18:21 UTC
The log is :
[pool-193-thread-1] ERROR com.amazon.alexa.avs.AVSAudioPlayer - Error playing:https:......m3u8

Please help me，thks！

**Comment by RogerZheng** [comment] 2017-04-10 08:12
this is application log：
4199 20:59:45.803 [pool-7-thread-1] ERROR com.amazon.alexa.avs.AVSAudioPlayer - Error playing: https://d29r7idq0wxsiz.cloudfront.ne
     t/DigitalMusicDeliveryService/HPS.m3u8?m=m&dmid=272028681&c=cf&f=ts&t=10&bl=256k&s=true&e1=1491814800000&e2=1491815700000&v=V2
     &h=16604b2fd8bd1b2d74e7e6799054cddff20d18784f7093e5a5ab9e2ce8112148
4200 20:59:45.831 [pool-7-thread-1] DEBUG com.amazon.alexa.avs.AudioPlayerTimer - Stopping AudioPlayerTimer
4201 20:59:45.833 [pool-7-thread-1] DEBUG com.amazon.alexa.avs.AudioPlayerStateMachine - PlaybackFailed
4202 20:59:45.834 [pool-7-thread-1] DEBUG com.amazon.alexa.avs.AudioPlayerTimer - Getting offset. Offset: 0
4203 20:59:45.882 [pool-7-thread-1] INFO  com.amazon.alexa.avs.http.AVSClient - Request metadata: 
4204 {
4205   "event" : {
4206     "header" : {
4207       "namespace" : "AudioPlayer",
4208       "name" : "PlaybackFailed",
4209       "messageId" : "cf7e249f-859b-4610-a42d-d0c5230a97fb"
4210     },
4211     "payload" : {
4212       "token" : "amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#6d1bf500-c659-414e-a16f-3ef26e1c1fc5:1",
4213       "currentPlaybackState" : {
4214         "token" : "amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#6d1bf500-c659-414e-a16f-3ef26e1c1fc5:1",
4215         "offsetInMilliseconds" : 0,
4216         "playerActivity" : "STOPPED"
4217       },
4218       "error" : {
4219         "type" : "MEDIA_ERROR_UNKNOWN",

**Comment by RogerZheng** [comment] 2017-04-11 08:41
this vlc log，It seems that is relative to tls：
[aa637260] core access error: net: connecting to d29r7idq0wxsiz.cloudfront.net port 443
[aa637260] core access error: connection succeeded (socket = 63)
[aa637e50] gnutls tls session error: TLS handshake: Resource temporarily unavailable, try again.
[aa637e50] gnutls tls session error: TLS handshake: Resource temporarily unavailable, try again.
[aa637e50] gnutls tls session error: TLS handshake: Resource temporarily unavailable, try again.
[aa637e50] gnutls tls session error: TLS handshake: Resource temporarily unavailable, try again.
[aa637e50] gnutls tls session error: TLS handshake: Success.
[aa637e50] gnutls tls session error: Certificate verification failure (0x0042)
[aa637e50] gnutls tls session error:  * Certificate not verified
[aa637e50] gnutls tls session error:  * Signer not found
[aa637e50] gnutls tls session error: 2 certificate(s) in the list
[aa637e50] gnutls tls session error: no known certificates for d29r7idq0wxsiz.cloudfront.net
[aa637e50] core tls session error: TLS client session handshake error
[aa637260] http access error: cannot establish HTTP/TLS session
[aa637260] core access error: no access modules matched
[ab092a48] core input error: open of `https://d29r7idq0wxsiz.cloudfront.net/DigitalMusicDeliveryService/HPS.m3u8?m=m&dmid=263660149
&c=cf&f=ts&t=10&bl=256k&s=true&e1=1491902100000&e2=1491903000000&v=V2&h=87b0481666bba0dc6c4ab82517f7da51feb036194b4fac5e1333071af30
f98fb' failed
[ab092a48] core input error: Your input can't be opened
[ab092a48] core input error: VLC is unable to open the MRL 'https://d29r7idq0wxsiz.cloudfront.net/DigitalMusicDeliveryService/HPS.m
3u8?m=m&dmid=263660149&c=cf&f=ts&t=10&bl=256k&s=true&e1=1491902100000&e2=1491903000000&v=V2&h=87b0481666bba0dc6c4ab82517f7da51feb03
6194b4fac5e1333071af30f98fb'. Check the log for details.

**Comment by scotthea-amazon** [comment] 2017-04-17 21:24
Hello Roger,

It looks like the problem is probably that your local certificates are out of date or otherwise incorrect.  you might try:
    sudo apt-get update && sudo apt-get upgrade
...which is a rather broad-brush update - or try something more targeted.

Hope that helps,
-SWH

**Comment by keleric** [comment] 2017-05-01 18:31
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.
Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.
Thanks!

**Closed by keleric** 2017-05-01 18:31 UTC
