### ISSUE TITLE
npm start failure

### ISSUE THREAD

**Issue by lukeZhangMengxi** [alexa/alexa-avs-sample-app#945] opened 2017-09-21 20:42 UTC
Hi I am following the instructions installing the sample app on my Mac.
When I run "npm install", I got the following error ( I have gone over the steps before step 8 again and nothing was wrong ).
I looked through the similar issues but could not fix it.

Thanks for any help.

Password:

> alexa-voice-service-sample-companion-service@1.0.0 start /Users/zhangmengxi/Tech/avs/sample-app/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

_tls_common.js:105
      c.context.setKey(options.key, options.passphrase);
                ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:105:17)
    at Server (_tls_wrap.js:804:25)
    at new Server (https.js:54:14)
    at Object.createServer (https.js:76:10)
    at Object.<anonymous> (/Users/zhangmengxi/Tech/avs/sample-app/alexa-avs-sample-app/samples/companionService/bin/www:31:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhangmengxi/.npm/_logs/2017-09-21T20_35_52_079Z-debug.log

**Comment by lukeZhangMengxi** [comment] 2017-09-21 20:43
and the debug log is:

Last login: Thu Sep 21 13:35:24 on ttys000
dhcp-206-87-194-186:~ zhangmengxi$ cd /Users/zhangmengxi/Tech/avs/sample-app/alexa-avs-sample-app/samples/companionService
dhcp-206-87-194-186:companionService zhangmengxi$ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /Users/zhangmengxi/Tech/avs/sample-app/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

_tls_common.js:105
      c.context.setKey(options.key, options.passphrase);
                ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:105:17)
    at Server (_tls_wrap.js:804:25)
    at new Server (https.js:54:14)
    at Object.createServer (https.js:76:10)
    at Object.<anonymous> (/Users/zhangmengxi/Tech/avs/sample-app/alexa-avs-sample-app/samples/companionService/bin/www:31:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

┌────────────────────────────────────────────────────────────────┐
│                    npm update check failed                     │
│              Try running with sudo or get access               │
│              to the local update config store via              │
│ sudo chown -R $USER:$(id -gn $USER) /Users/zhangmengxi/.config │
└────────────────────────────────────────────────────────────────┘

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhangmengxi/.npm/_logs/2017-09-21T20_35_32_251Z-debug.log
dhcp-206-87-194-186:companionService zhangmengxi$ sudo npm start
Password:

> alexa-voice-service-sample-companion-service@1.0.0 start /Users/zhangmengxi/Tech/avs/sample-app/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

_tls_common.js:105
      c.context.setKey(options.key, options.passphrase);
                ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:105:17)
    at Server (_tls_wrap.js:804:25)
    at new Server (https.js:54:14)
    at Object.createServer (https.js:76:10)
    at Object.<anonymous> (/Users/zhangmengxi/Tech/avs/sample-app/alexa-avs-sample-app/samples/companionService/bin/www:31:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhangmengxi/.npm/_logs/2017-09-21T20_35_52_079Z-debug.log
dhcp-206-87-194-186:companionService zhangmengxi$ vim /Users/zhangmengxi/.npm/_logs/2017-09-21T20_35_52_079Z-debug.log

13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid alexa-voice-service-sample-companion-service@1.0.0
15 verbose cwd /Users/zhangmengxi/Tech/avs/sample-app/alexa-avs-sample-app/samples/companionService
16 verbose Darwin 15.4.0
17 verbose argv "/usr/local/Cellar/node/8.5.0/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.5.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by balaraju1278** [comment] 2017-09-22 10:29
you are getting this error while making http request ,did you cross check these things,when you are creating security profile in avs you are entered allowed origins and return uri these things should match with config.js file and congif.json file

**Comment by mradulan** [comment] 2017-09-22 21:24
please verify the config.js and config.json

**Comment by lukeZhangMengxi** [comment] 2017-09-22 22:31
I checked the config.js and config.json file, and there was a mistake inside my config.json file.
I corrected the typo and get following error when I run "npm install":

Password:
npm WARN saveError ENOENT: no such file or directory, open '/Users/zhangmengxi/Tech/avs/sample-app/alexa-avs-sample-app/samples/javaclient/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/zhangmengxi/Tech/avs/sample-app/alexa-avs-sample-app/samples/javaclient/package.json'
npm WARN javaclient No description
npm WARN javaclient No repository field.
npm WARN javaclient No README data
npm WARN javaclient No license field.

up to date in 0.078s

**Comment by lukeZhangMengxi** [comment] 2017-09-22 22:46
I did find an mistake in my config.js file, but after the correction I am still having the same problem. My ssl.cnf is:

[req]
distinguished_name      = req_distinguished_name
prompt                  = no

[v3_req]
subjectAltName          = @alt_names

[alt_names]
DNS.1                   = localhost
IP.1                    = 127.0.0.1
IP.2                    = 10.0.2.2

[req_distinguished_name]
commonName              = $ENV::COMMON_NAME                 # CN=
countryName             = CA                 # C=
stateOrProvinceName     = BC            # ST=
localityName            = Vancouver                         # L=
organizationName        = XXX                 # O=
organizationalUnitName  = XXXX          # OU=

**Comment by mradulan** [comment] 2017-09-22 22:46
the file package.json should be in {REFERENCE_IMPLEMENTATION}/samples/companionService/
Can you do a "ls" in {REFERENCE_IMPLEMENTATION}/samples/companionService/ and "ls" in {REFERENCE_IMPLEMENTATION}/samples/javaclient.

**Comment by lukeZhangMengxi** [comment] 2017-09-22 22:50
I was running npm install from {REFERENCE_IMPLEMENTATION}/samples/javaclient. 
I have noticed that mistake. Thanks though.
But I am still having the same error as the beginning

"ls" in /samples/javaclient
README.txt		log4j2.xml		ssl.cnf
certs			package-lock.json	template_config_json
config.json		pom.xml			template_generate_sh
generate.bat		pom_other.xml		template_ssl_cnf
generate.sh		pom_pi.xml
install-java8.sh	src



"ls" in /samples/companionService/:

app.js			config.js		package.json
authentication.js	node_modules		template_config_js
bin			package-lock.json

**Comment by mradulan** [comment] 2017-09-22 23:05
can you remove the file package-lock.json, and run "npm install" from {REFERENCE_IMPLEMENTATION}/samples/companionService

**Comment by lukeZhangMengxi** [comment] 2017-09-22 23:48
I can run "npm install" with no errors.
And I removed package-lock.json, then when I run "npm install" it generated
a new package-lock.json file.
After that I run "npm start" and got the same error as before.

2017-09-22 16:05 GMT-07:00 Mradula Nayak <notifications@github.com>:

**Comment by mradulan** [comment] 2017-09-23 00:05
It looks similar to #190 . Can you check the node version by doing a "node -v". Also refer the issue #190

**Comment by balaraju1278** [comment] 2017-09-23 04:21
That looks like you did a mistake in path configuration, Which flatform you are using

**Comment by mradulan** [comment] 2017-09-25 17:39
Hi @lukeZhangMengxi , is the issue resolved?

**Comment by lukeZhangMengxi** [comment] 2017-09-25 20:19
I am sorry I was out home on the last weekend. The issue has not been resolved yet.

I am using MAC OS X EI Captain 10.11.4

On my terminal, "node -v" gives:
       v8.5.0

I do not quite believe it is a problem about node, since the error message mentions that "npm ERR! This is probably not a problem with npm. "

**Comment by lukeZhangMengxi** [comment] 2017-09-25 20:54
Oh, I solved it.

There was a typo on my config.js ...

I am so sorry that I did not find it earlier.

**Comment by mradulan** [comment] 2017-09-25 20:55
Hi @lukeZhangMengxi , if the issue is resolved, can you close the issue. Thanks.

**Closed** 2017-09-26 22:56 UTC
